theme: jekyll-theme-slate
baseurl: "/engineer" # the subpath of your site, e.g. /blog
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge