title: Diego Tuzi Website
email: diegotuzi@gmail.com
description: >- # this means to ignore newlines until "url:"
  Diego Tuzi Telecomunication Engineer Personal Website
url: "https://diegotuzi.github.io/"
twitter_username: DiegoTuzi
github_username:  diegotuzi

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
lsi: false
safe: true
source: [diegotuzi.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: assets/css